unit TDA_2;
interface
Procedure TDAT;
Procedure TEXTY;
Procedure SLICEDP;
Procedure WCTE;
Procedure LEVE;
Procedure PLAY;
Procedure HISC;
Procedure SPEE;
Procedure PANEL;
Procedure MOWER;
implementation

Procedure TDAT; external; {$L TDAT.OBJ} Procedure TEXTY; external; {$L TEXTY.OBJ}
Procedure SLICEDP; external; {$L SLICEDp.OBJ} Procedure WCTE; external; {$L WCTE.OBJ}
Procedure LEVE; external; {$L LEVE.OBJ} Procedure PLAY; external; {$L PLAY.OBJ}
Procedure HISC; external; {$L HISC.OBJ} procedure SPEE; external; {$L SPEE.OBJ}
Procedure PANEL; external; {$L PANEL.OBJ} Procedure MOWER; external; {$L MOWER.OBJ}
end.