Unit SS_GFX3;

Interface
Procedure sky_mez;
Procedure sky_stu;
Procedure sky_ben;
Procedure sky_plan;
Procedure sky_cld;
Procedure sky_clds;
Procedure sky_bird;
Procedure sky_kite;

Implementation
Procedure sky_mez; external;
{$L sky_mez.obj}
Procedure sky_stu; external;
{$L sky_stu.obj}
Procedure sky_ben; external;
{$L sky_ben.obj}
Procedure sky_plan; external;
{$L sky_plan.obj}
Procedure sky_cld; external;
{$L sky_cld.obj}
Procedure sky_clds; external;
{$L sky_clds.obj}
Procedure sky_bird; external;
{$L sky_bird.obj}
Procedure sky_kite; external;
{$L sky_kite.obj}
end.

