Unit SS_GFX4;

Interface
Procedure for_mez;
Procedure for_gaz;
Procedure for_wes;
Procedure for_gras;
Procedure for_grs2;
Procedure for_tree;
Procedure for_tre2;
Procedure for_spid;
Procedure for_sqr;
Procedure for_leav;

Implementation
Procedure for_mez; external;
{$L for_mez.obj}
Procedure for_gaz; external;
{$L for_gaz.obj}
Procedure for_wes; external;
{$L for_wes.obj}
Procedure for_gras; external;
{$L for_gras.obj}
Procedure for_grs2; external;
{$L for_grs2.obj}
Procedure for_tree; external;
{$L for_tree.obj}
Procedure for_tre2; external;
{$L for_tre2.obj}
Procedure for_spid; external;
{$L for_spid.obj}
Procedure for_sqr; external;
{$L for_sqr.obj}
Procedure for_leav; external;
{$L for_leav.obj}
end.


